name: Debug R2 Env

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print env
        env:
          R2_KEY: drhouse.jpg
        run: |
          echo "R2_KEY=$R2_KEY"
